# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Botay

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_and_zip:
    name: Test and collect files to zip
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --exclude botay-infra,venv . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 --exclude botay-infra,venv . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Create archive of dependencies
      run: |
        set -eux pipefail
        pip install -t lib -r requirements.txt
        (cd lib; zip ../lambda_function.zip -r .)
        zip lambda_function.zip -ur app/.
        rm -rf lib
    - name: Upload zip file artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambda_function
        path: lambda_function.zip

  deploy_on_aws:
    name: Deploy on AWS lambda
    runs-on: ubuntu-latest
    needs: test_and_zip
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Download lambda lambda_function.zip
        uses: actions/download-artifact@v3
        with:
          name: lambda_function
      - name: Upload to S3
        run: aws s3 cp lambda_function.zip s3://cdk-hnb659fds-assets-079202211282-us-east-1/lambda_function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy new lambda
        run: aws lambda update-function-code --function-name botay_lambda --s3-bucket cdk-hnb659fds-assets-079202211282-us-east-1 --s3-key lambda_function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
